unless defined?(::Rake)
  OMEGA_DISCORD_APP_ID = ENV['OMEGA_DISCORD_APP_ID']
  OMEGA_DISCORD_SECRET = ENV['OMEGA_DISCORD_SECRET']
  OMEGA_DISCORD_BOT_TOKEN = ENV['OMEGA_DISCORD_BOT_TOKEN']

  OmegaDiscordBot.run!
#  ShababDiscordBot.run!(ENV['SHABAB_DISCORD_BOT_TOKEN'], ENV['SHABAB_DISCORD_APP_ID'])
end

